TechnologyEnhancedLearning/LearningHub.Nhs.UserApi

Auth/LearningHub.Nhs.Auth/appsettings.json, Auth/LearningHub.Nhs.Auth/wwwroot/images/client-logos/dls.svg
Added client configuration for DLS. This will allow DLS to use the Authentication service.
=> Added client configuration for DLS

README.md
[TD-972](https://hee-tis.atlassian.net/browse/TD-972)
Adds some basic intro, setup and contribute instructions to the UserAPI project readme.
-----
I have:
[TD-972]: https://hee-tis.atlassian.net/browse/TD-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-972 Populate repository readme with basic content

LearningHub.Nhs.UserApi/Program.cs
=> Removed the space

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, Auth/LearningHub.Nhs.Auth/Views/Shared/LearningHub/_FooterPartial.cshtml, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
=> Merge LH orion Changes to master

Auth/LearningHub.Nhs.Auth/Controllers/AccountController.cs
[_TD-3841_](https://hee-tis.atlassian.net/browse/TD-3841)
Fixed the issue with null context in the login action methods
-----
I have:
=> TD-3841 Logs are Getting Saved in Production Log AUTH Errors

Auth/LearningHub.Nhs.Auth/appsettings.json, Auth/LearningHub.Nhs.Auth/wwwroot/images/client-logos/dls.svg
=> Merge Releases/reticulum  to RC 

LearningHub.Nhs.UserApi/Controllers/JobRoleController.cs
=> Merge RC Changes to LH PHoenix

LearningHub.Nhs.UserApi.Services/ElfhUserService.cs
TD-3339
Remove spaces from User Name
-----
I have:
=> TD-3339-remove spaces  From Username

Auth/LearningHub.Nhs.Auth/Controllers/OpenAthensController.cs, Auth/LearningHub.Nhs.Auth/ServiceCollectionExtension.cs, Auth/LearningHub.Nhs.Auth/appsettings.json
https://hee-tis.atlassian.net/browse/TD-4111
elfh authentication errors in error log (PR Draft version)
-----
I have:
=> TD-4111: Log table flooded with error has been handled(PR Draft version)

LearningHub.Nhs.UserApi.Services/ElfhUserService.cs, LearningHub.Nhs.UserApi/Controllers/JobRoleController.cs
=>  Merge Releases/lh scorpius  to Rc Branch

Auth/LearningHub.Nhs.Auth/Configuration/LearningHubResourceStore.cs, Auth/LearningHub.Nhs.Auth/appsettings.json
=> Added userprofileclient config and learningcredentialsapi scope

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
=> Model Version Update

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
Reverts TechnologyEnhancedLearning/LearningHub.Nhs.UserApi#46
=> Revert "Model Version Update"

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
=> model version update-RC

Auth/LearningHub.Nhs.Auth/Views/Shared/LearningHub/_Layout.cshtml
=> Set login page primary language

Auth/LearningHub.Nhs.Auth/Views/Shared/_ValidationScriptsPartial.cshtml
https://hee-tis.atlassian.net/browse/TD-4184
-----
I have:
=> TD-4184:Focus doesn't move to field or error on submit

Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/DateInput/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/ErrorSummary/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/RadioList/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/TextInput/Default.cshtml
=> View component model version updated

Auth/LearningHub.Nhs.Auth/Views/Account/LHLogin.cshtml
TD-4184
Keep current values
-----
I have:
=> TD-4184-Focus doesn't move to field or error on submit (Keep current values)

Auth/LearningHub.Nhs.Auth/Controllers/AccountController.cs
TD-4184
DIG414: Focus doesn't move to field or error on submit
-----
I have:
=> TD-4184-DIG414: Focus doesn't move to field or error on submit

.github/workflows/continuous-integration-workflow.yml, Auth/LearningHub.Nhs.Auth/Controllers/AccountController.cs, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, Auth/LearningHub.Nhs.Auth/Views/Account/LHLogin.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/DateInput/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/ErrorSummary/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/RadioList/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/Components/TextInput/Default.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/LearningHub/_Layout.cshtml, Auth/LearningHub.Nhs.Auth/Views/Shared/_ValidationScriptsPartial.cshtml, Auth/LearningHub.Nhs.Auth/package.json, LearningHub.Nhs.UserApi.Repository/Extentions/IQueryableExtensions.cs
=> Merge Begonia changes to master

.github/workflows/continuous-integration-workflow.yml, Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj, LearningHub.Nhs.UserApi/ServiceMappings.cs
https://hee-tis.atlassian.net/browse/TD-4168
Upgrade LH solutions to .NET 8 (LTS) 
-----
I have:
=> TD-4168: Upgrade LH solutions to .NET 8 (LTS)

.github/workflows/continuous-integration-workflow.yml, Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj, LearningHub.Nhs.UserApi/ServiceMappings.cs
Merge Release v1.1.0 changes to RC
-----
I have:
=> Merge Release v1.1.0 changes to RC

Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
Reverting automapper upgrade to inline with Models project
=> Reverting automapper upgrade to inline with Models project

Auth/LearningHub.Nhs.Auth/appsettings.json
TD-5385 JIRA link
_TD-5385_
_Moodle client config section has been added to the appsettings.json file._
-----
I have:
=> Added moodle client configuration to appsettings.json

Auth/LearningHub.Nhs.Auth/appsettings.json
TD-5385 JIRA link
_TD-5385_
_Change the RedirectUris for the moodle client to the correct value._
-----
I have:
=> Corrected RedirectUris for moodle client

Auth/LearningHub.Nhs.Auth/Controllers/AccountController.cs
_TD-###_
Reverted the code to test the error log issues in the test environment
-----
I have:
=> Reverted the test code

Auth/LearningHub.Nhs.Auth/Views/Account/LHLogin.cshtml
_[TD-4303](https://hee-tis.atlassian.net/browse/TD-4303)_
Changes in login page part of adding automated accessibility tests for LH
-----
I have:
[TD-4303]: https://hee-tis.atlassian.net/browse/TD-4303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4303: Changes in login page part of adding automated accessibility tests for LH

Auth/LearningHub.Nhs.Auth/package-lock.json, Auth/LearningHub.Nhs.Auth/package.json
=> Automatic version update dependabot changes to RC

LearningHub.Nhs.UserApi.Repository/LH/ExternalSystemUserRepository.cs
https://hee-tis.atlassian.net/browse/TD-5407
Corrected the data type
-----
I have:
=> Corrected the datatype

LearningHub.Nhs.UserApi.Services/RegistrationService.cs
_TD-###_
Replaced EF call with SP call to fix SQL exception
-----
I have:
=> Modified EF call with SP call

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/Controllers/AccountController.cs, Auth/LearningHub.Nhs.Auth/Interfaces/IUserService.cs, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, Auth/LearningHub.Nhs.Auth/Services/UserService.cs, Auth/LearningHub.Nhs.Auth/Views/Account/AlreadyActiveSession.cshtml, LearningHub.Nhs.UserApi.Repository.Interface/IUserHistoryRepository.cs, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Repository/UserHistoryRepository.cs, LearningHub.Nhs.UserApi.Services.Interface/IUserHistoryService.cs, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Services/UserHistoryService.cs, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/Controllers/UserHistoryController.cs, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
https://hee-tis.atlassian.net/browse/TD-3734
Handled concurrent user login session by using DB.
-----
I have:
=> TD-3734: Concurrent Sessions Allowed

Hee.UserProfile.Database/Hee.UserProfile.Database.sqlproj
https://hee-tis.atlassian.net/browse/TD-5492
Upgraded .NET Framework Version For Database Project to 4.8
-----
I have:
=> TD-5492: Upgrade .NET Framework Version For Database Project

Auth/LearningHub.Nhs.Auth/package-lock.json, Auth/LearningHub.Nhs.Auth/package.json
=> Merge Automatic version update dependabot to RC

Auth/LearningHub.Nhs.Auth/package-lock.json, Auth/LearningHub.Nhs.Auth/package.json
…(#180)
Bumps [@babel/core](https://github.com/babel/babel/tree/HEAD/packages/babel-core) from 7.27.1 to 7.27.3.
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.27.3/packages/babel-core)
---
updated-dependencies:
- dependency-name: "@babel/core" dependency-version: 7.27.3 dependency-type: direct:development update-type: version-update:semver-patch ...
_TD-###_
-----
(Leave tasks …
=> Merge dependabot changes to RC

Auth/LearningHub.Nhs.Auth/package-lock.json, Auth/LearningHub.Nhs.Auth/package.json, Directory.Packages.props
=> Automatic version update dependabot To RC

Auth/LearningHub.Nhs.Auth/package-lock.json, Auth/LearningHub.Nhs.Auth/package.json
Reverts TechnologyEnhancedLearning/LearningHub.Nhs.UserApi#197
=> Revert "Automatic version update dependabot To RC"

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/IOpenApiHttpClient.cs, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/ElfhUserService.cs, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Services/OpenApiConfig.cs, LearningHub.Nhs.UserApi.Services/OpenApiHttpClient.cs, LearningHub.Nhs.UserApi.Services/RegistrationService.cs, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj, LearningHub.Nhs.UserApi/Program.cs, LearningHub.Nhs.UserApi/ServiceCollectionExtension.cs, LearningHub.Nhs.UserApi/ServiceMappings.cs
_TD-5675_
Replaced Auth service SMTP notifications by GovNotify services.
-----
I have:
=> TD-5675: Replacement of SMTP notifications by GovNotify service.

Auth/LearningHub.Nhs.Auth.Tests/LearningHub.Nhs.Auth.Tests.csproj, Auth/LearningHub.Nhs.Auth/LearningHub.Nhs.Auth.csproj, Directory.Build.props, Directory.Packages.props, LearningHub.Nhs.UserApi.Repository.Interface/LearningHub.Nhs.UserApi.Repository.Interface.csproj, LearningHub.Nhs.UserApi.Repository/LearningHub.Nhs.UserApi.Repository.csproj, LearningHub.Nhs.UserApi.Services.Interface/LearningHub.Nhs.UserAPI.Services.Interface.csproj, LearningHub.Nhs.UserApi.Services.UnitTests/LearningHub.Nhs.UserApi.Services.UnitTests.csproj, LearningHub.Nhs.UserApi.Services/LearningHub.Nhs.UserApi.Services.csproj, LearningHub.Nhs.UserApi.Shared/LearningHub.Nhs.UserApi.Shared.csproj, LearningHub.Nhs.UserApi.UnitTests/LearningHub.Nhs.UserApi.UnitTests.csproj, LearningHub.Nhs.UserApi/LearningHub.Nhs.UserApi.csproj
=> Revert  CPM from RC

Auth/LearningHub.Nhs.Auth/appsettings.json
_TD-5801_
_moodlemooc stanza has been added to the appsettings.json file. Pipeline variables have been added to the DevOps pipeline for the production deployment of this._
-----
I have:
=> Added moodlemooc stanza to appsettings.json
